apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  selector:
    app: product
  type: ClusterIP # LoadBalancer # NodePort #
  ports:
    - protocol: TCP
      name: m-http
      port: 80
      targetPort: 3000