apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  selector:
    app: inventory
  type: ClusterIP # LoadBalancer # NodePort #
  ports:
    - protocol: TCP
      name: m-http
      port: 80
      targetPort: 3000